//
//  DetailsInteractor.swift
//  zap-challenge-viper
//
//  Created by Renato Medina on 01/04/19.
//  Copyright (c) 2019 Renato Medina. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsInteractor {
}

// MARK: - Extensions -

extension DetailsInteractor: DetailsInteractorInterface {
}
