//
//  DetailsPresenter.swift
//  zap-challenge-viper
//
//  Created by Renato Medina on 01/04/19.
//  Copyright (c) 2019 Renato Medina. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsPresenter {

    // MARK: - Private properties -

    private unowned let _view: DetailsViewInterface
    private let _wireframe: DetailsWireframeInterface
    private let _interactor: DetailsInteractorInterface

    
    private var item: Property  {
        didSet {
            setup()
        }
    }
    
    // MARK: - Lifecycle -
    
    init(wireframe: DetailsWireframeInterface, view: DetailsViewInterface, interactor: DetailsInteractorInterface, property: Property) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        item = property
    }
    
    private func setup() {
        _view.setImage(url: item.images.first)
        _view.setTitle(title: item.address.city)
        _view.setDescription(description: item.listingStatus)
    }
}

// MARK: - Extensions -

extension DetailsPresenter: DetailsPresenterInterface {
    
    func viewDidLoad() {
        setup()
    }
    
}
