//
//  DetailsInterfaces.swift
//  zap-challenge-viper
//
//  Created by Renato Medina on 01/04/19.
//  Copyright (c) 2019 Renato Medina. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailsNavigationOption {
}

protocol DetailsWireframeInterface: WireframeInterface {
    func navigate(to option: DetailsNavigationOption)
}

protocol DetailsViewInterface: ViewInterface {
    func setImage(url: String?)
    func setTitle(title: String?)
    func setDescription(description: String?)
}

protocol DetailsPresenterInterface: PresenterInterface {
}

protocol DetailsInteractorInterface: InteractorInterface {
}
