//
//  ListInteractor.swift
//  zap-challenge-viper
//
//  Created by Renato Medina on 29/03/19.
//  Copyright (c) 2019 Renato Medina. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ListInteractor {
    private let _apiClient = APIClient(networkClient: NetworkClient())
}

// MARK: - Extensions -

extension ListInteractor: ListInteractorInterface {
    
    func getProperties(completion: @escaping ([Property]) -> ()) {
        return _apiClient.fetchProperties(completion:completion)
    }
    
    
}
