//
//  LoginInteractor.swift
//  zap-challenge-viper
//
//  Created by Renato Medina on 04/04/19.
//  Copyright (c) 2019 Renato Medina. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation


enum LoginValidationsType {
    case wrongEmail
    case wrongPassword
    case success
}

final class LoginInteractor {
    var loginDataManager: LoginDataManagerInterface
    
    init(dataManager: LoginDataManagerInterface) {
        self.loginDataManager = dataManager
    }
}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    
    func isLogged() -> Bool {
        return loginDataManager.isLogged()
    } 
    
    func login(email: String?, password: String?) -> LoginValidationsType {
        
        guard let email = email, email.isValidEmail()  else {
            return .wrongEmail
        }
        
        guard let password = password, password.isStrongPaswword()  else {
            return .wrongPassword
        }
        
        loginDataManager.saveEmail(email: email)
        return .success
    }
    
    func logout() {
        loginDataManager.clear()
    }
}
